version: '3.7'
services:
    mongo:
        image: mongo
        volumes:
            - mongo-vol:/data/db
    mongoview:
        image: mongo-express
        restart: on-failure
        ports:
            - "8081:8081"
        depends_on:
            - mongo
        environment:
            - ME_CONFIG_BASICAUTH_USERNAME=tagesschau
            - ME_CONFIG_BASICAUTH_PASSWORD=tagesschau
    crawler:
        container_name: ts-crawler
        build: ./initCrawl/
        init: true
        restart: on-failure
        depends_on:
            - mongo
    revision:
        container_name: ts-revision
        build: ./revisionCrawl/
        init: true
        restart: on-failure
        depends_on:
            - mongo

volumes:
    mongo-vol:
